### PR TITLE
chore: update readme

### PR DESCRIPTION
**Pull request by PernDev**
remove not

### CODE REVIEW

**Comment by MeeDev01** [comment]
hoe to do this

**Comment by MeeDev01** [comment]
how to eran chievement like this

**Comment by PernDev** [comment]
> how to eran chievement like this
 contact me if you want it

**Comment by MeeDev01** [comment]
what is you phone number

**Comment by PernDev** [comment]
> what is you phone number2099999999999

**Comment by MeeDev01** [comment]
I WIALL CALL YOU

**Comment by PernDev** [comment]
> I WIALL CALL YOU
OK

**Comment by MeeDev01** [comment]
SDFSG

**Comment by PernDev** [comment]
> SDFSG

GDSFGDRZFGDZFG

**Comment by MeeDev01** [comment]
GDFGFGERSXZG

**Comment by PernDev** [comment]
> GDFGFGERSXZG

FGHFGHFXGHXDFGH

**Comment by MeeDev01** [comment]
> > GDFGFGERSXZG
> 
> FGHFGHFXGHXDFGH

GFHXFGHXFGHXGH

**Comment by PernDev** [comment]
> > > GDFGFGERSXZG
> > 
> > 
> > FGHFGHFXGHXDFGH
> 
> GFHXFGHXFGHXGH

FXGHXFGHXFGH

**Comment by MeeDev01** [comment]
> > > > GDFGFGERSXZG
> > > 
> > > 
> > > FGHFGHFXGHXDFGH
> > 
> > 
> > GFHXFGHXFGHXGH
> 
> FXGHXFGHXFGH

RGDFGDSZXFG

**Comment by PernDev** [comment]
> > > > > GDFGFGERSXZG
> > > > 
> > > > 
> > > > FGHFGHFXGHXDFGH
> > > 
> > > 
> > > GFHXFGHXFGHXGH
> > 
> > 
> > FXGHXFGHXFGH
> 
> RGDFGDSZXFG

FCDGDFGSZFDGSFDG

**Comment by MeeDev01** [comment]
GDFGDFGSZÎÏG

**Comment by PernDev** [comment]
GDFGXDFGDFG

> GDFGDFGSZÎÏG

GDZFGDZFGDSZFG

**Comment by MeeDev01** [comment]
> > > > > > GDFGFGERSXZG
> > > > > 
> > > > > 
> > > > > FGHFGHFXGHXDFGH
> > > > 
> > > > 
> > > > GFHXFGHXFGHXGH
> > > 
> > > 
> > > FXGHXFGHXFGH
> > 
> > 
> > RGDFGDSZXFG
> 
> FCDGDFGSZFDGSFDG

FGZFDGDZFGSZDFGZDFG

**Comment by PernDev** [comment]
> > > > > > > GDFGFGERSXZG
> > > > > > 
> > > > > > 
> > > > > > FGHFGHFXGHXDFGH
> > > > > 
> > > > > 
> > > > > GFHXFGHXFGHXGH
> > > > 
> > > > 
> > > > FXGHXFGHXFGH
> > > 
> > > 
> > > RGDFGDSZXFG
> > 
> > 
> > FCDGDFGSZFDGSFDG
> 
> FGZFDGDZFGSZDFGZDFG

DVZSDFVSDVSDASDFADFAZDFG

**Comment by MeeDev01** [comment]
TGSDFGSDXFGSEZDFG

**Comment by PernDev** [comment]
> TGSDFGSDXFGSEZDFG

DFGSZFDGBZDFGZGG

**Pull request merged**
